import {PluginConfig, PluginOptions} from '@sdr/core';
import * as ejs from 'ejs';

export function plugin(options: PluginOptions, config: {baseClientLocation: string}) {
  return ejs.render(
    // language=EJS
    `/* This file was generated by https://github.com/schema-driven-rest/plugin-fetch */
/* tslint:disable */
import {BaseClient,ControllerOptions} from '<%=baseClientLocation%>';

<% for(const type of types) { %>
    <%
        const controllerName = type.name;
        const {
            parameters: [{value: controllerPath}],
        } = type.directives.find(a => a.name === 'controller');

    %>

export class <%= type.name %>Client extends BaseClient {

    constructor(options:ControllerOptions){
        super(options);
    }

    <% for(const method of type.methods) { %>
        <%
            const requestDirective = method.directives.find(a => a.name === 'request');
            const requiresAuth = !!method.directives.find(a => a.name === 'auth');
            const methodName = method.name;
            const requestType = method.arguments[0]?method.arguments[0].type:null;
            const returnType = method.returnType.type;

            if (!requestDirective) {
                throw \`This plugin requires all methods to have a request directive. \${method.name} is missing.\`;
            }
            const methodPath = requestDirective.parameters.find(parameter => parameter.name === 'path').value;
            const methodType = requestDirective.parameters.find(parameter => parameter.name === 'method').value;

        %>

    async <%= methodName %>(<%= (requestType?'model: '+requestType:'') %>):Promise<<%= returnType %>>{
        try{
            let url = this.options.baseUrl + '/<%=controllerPath%>/<%= methodPath %>?';
            const options = {
                method: "<%= methodType %>",
                headers: {
                    "Content-Type": "application/json",
                    "Accept": "application/json"
                }
            } as RequestInit;
            <% if(requestType) {%>
            <% if(methodType.toUpperCase() === 'GET') { %>
                url += Object.keys(model)
                .filter(key => !!(model as any)[key])
                .map(key => \`\${key}=\${encodeURIComponent((model as any)[key])}\`)
                .join('&');
            <% } else { %>
                options.body = JSON.stringify(model);
            <% } %>
            <% } %>

            const response = await fetch(url, await this.transformOptions(options));

            const status = response.status;
            const headers: any = {};

            if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => headers[k] = v); };

            const responseText = await response.text();

            if (status === 200) {
                return JSON.parse(responseText)
            }

            else {
                try {
                    const body = JSON.parse(responseText);
                    throw body;
                } catch (ex) {
                    throw ex;
                }
            }
        }
        catch(ex){
            throw ex;
        }
    }
    <% } %>
}


<% } %>
`,
    {
      types: options.types.filter(a=>a.directives.find(a => a.name === 'controller')),
      baseClientLocation: config.baseClientLocation,
    },
    {}
  );
}

export const config: PluginConfig = {
  dependsOn: ['@sdr/controller'],
};
