/* This file was generated by https://github.com/schema-rest-driven/plugin-serverless-api-base */

import {UserController} from './api/UserController';

export const User_login = new UserController().login;

export const User_getUser = new UserController().getUser;

export const User_updateUser = new UserController().updateUser;
