service:
  name: simple-serverless

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 29
  memorySize: 512
  region: us-west-2

functions:
  ${file(./serverless-api.yaml)}
